#!/bin/sh

set -e # exit on any error

case "$(uname -s)" in
    Linux*)     OS=Linux;;
    Darwin*)    OS=Mac;;
    CYGWIN*)    OS=Windows;;
    MINGW*)     OS=Windows;;
    MSYS_NT*)   OS=Windows;;
    *)          OS=Unknown
esac

if [ ${OS} = Windows ]; then
  DIR=$(dirname "$(readlink -f -- "$0" || cygpath -a -- "$0")")
  PATH=$DIR/idris2_app:$PATH # The Windows equivalent of LD_LIBRARY_PATH is PATH.
elif [ ${OS} = Mac ]; then
  DIR=$(zsh -c 'printf %s "$0:A:h"' "$0")
else
  DIR=$(dirname "$(readlink -f -- "$0")")
fi

export LD_LIBRARY_PATH="$DIR/idris2_app:$LD_LIBRARY_PATH"
export DYLD_LIBRARY_PATH="$DIR/idris2_app:$DYLD_LIBRARY_PATH"
export IDRIS2_INC_SRC="$DIR/idris2_app"
"$DIR/idris2_app/idris2" "$@"
