#!/bin/sh

case `uname -s` in
    OpenBSD|FreeBSD|NetBSD)
        DIR="`grealpath $0`"
        ;;

    *)
        DIR="`realpath $0`"
        ;;
esac

if test -z "${SCHEME}"; then
    echo "SCHEME env var is not set" >&2
    exit 1
fi

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`dirname "$DIR"`/"idris2_app""
export PATH="`dirname "$DIR"`/"idris2_app":$PATH"
${SCHEME} --script "`dirname $DIR`"/"idris2_app/idris2-boot.so" "$@"
