#!/bin/sh

case `uname -s` in
    OpenBSD|FreeBSD|NetBSD)
        DIR="`grealpath $0`"
        ;;

    *)
        DIR="`realpath $0`"
        ;;
esac

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`dirname "$DIR"`/"idris2_app""
export PATH="`dirname "$DIR"`/"idris2_app":$PATH"
"`dirname $DIR`"/"idris2_app/idris2-boot" "$@"
