#!/bin/sh

echo $IDRIS2_SUPPORT
make support
cp support/c/libidris2_support.so bootstrap/idris2-boot_app
cd bootstrap

sed s/libidris2_support.so/$IDRIS2_SUPPORT/g idris2-boot_app/idris2sh.ss > idris2-boot_app/idris2-boot.ss
${SCHEME} --script compile.ss

mkdir -p ../build/exec
mkdir -p ../build/exec/idris2-boot_app
install idris2-boot ../build/exec/idris2sh
install idris2-boot_app/* ../build/exec/idris2-boot_app
