all:
	${IDRIS2} --build prelude.ipkg

install:
	${IDRIS2} --install prelude.ipkg

install-with-src:
	${IDRIS2} --install-with-src prelude.ipkg

docs:
	${IDRIS2} --mkdoc prelude.ipkg

clean:
	$(RM) -r build
