all:
	${IDRIS2} --build papers.ipkg

install:
	${IDRIS2} --install papers.ipkg

install-with-src:
	${IDRIS2} --install-with-src papers.ipkg

docs:
	${IDRIS2} --mkdoc papers.ipkg

clean:
	$(RM) -r build
