all:
	${IDRIS2} --build contrib.ipkg

install:
	${IDRIS2} --install contrib.ipkg

install-with-src:
	${IDRIS2} --install-with-src contrib.ipkg

docs:
	${IDRIS2} --mkdoc contrib.ipkg

clean:
	$(RM) -r build
