---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD001: false
MD003: false
MD004: false                  # Unordered list style
MD007:
  indent: 2                   # Unordered list indentation
MD013:
  line_length: 400            # Line length 80 is far to short
MD024:
  siblings_only: true         # allow duplicate headings in CHANGELOG
MD026:
  punctuation: ".,;:。，；:"   # List of not allowed
MD029: false                  # Ordered list item prefix
MD033: false                  # Allow inline HTML
MD036: false                  # Emphasis used instead of a heading
MD041: false                  # First line in file should be a top level heading
MD044:                        # Proper names should have the correct capitalization
  code_blocks: false
  html_elements: false
MD046: false                  # Idented code block instead of fenced off

#################
# Rules by tags #
#################
blank_lines: false  # Error on blank lines
