all:
	${IDRIS2} --build linear.ipkg

install:
	${IDRIS2} --install linear.ipkg

install-with-src:
	${IDRIS2} --install-with-src linear.ipkg

docs:
	${IDRIS2} --mkdoc linear.ipkg

clean:
	$(RM) -r build
